### ISSUE TITLE
窗口移动

### ISSUE THREAD

**Issue by ch4O3** [xijaja/wails-template-vue3#1]
请教个问题，老哥。这个模版为什么在程序中选择文本选择不上，而是整体窗口会被移动

**Comment by xijaja** [comment]
关于文本选中，因为 index.html 文件中设置了一个 tailwindcss 类 “select-none”，考虑到桌面软件比如菜单上的文字不应该被选中，所以增加了此类，你可以移除此类名，然后在必要的位置添加。

关于窗口移动，增加了 style="--wails-draggable:drag" 如果你是 mac 系统，隐藏了窗口标题栏之后，这使窗口仍然可以被移动，你可以去除并在需要的元素上添加。
