### ISSUE TITLE
模版报错

### ISSUE THREAD

**Issue by AduraK2** [xijaja/wails-template-vue3#2]
➜  test-wails-app wails dev
Wails CLI v2.8.1

Executing: go mod tidy
  • Generating bindings: Done.
  • Installing frontend dependencies: Done.
  • Compiling frontend:     
    > test-wails-app@0.0.0 build
    > vue-tsc && vite build
    
    
    
    /Users/chenw/Desktop/WailsProject/test-wails-app/frontend/node_modules/vue-tsc/bin/vue-tsc.js:68
    			throw err;
    			^
    Search string not found: "for (const existingRoot of buildInfoVersionMap.roots) {"
    (Use `node --trace-uncaught ...` to show where the exception was thrown)
    
    Node.js v18.16.0
    

  ERROR   exit status 1
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
这个问题要怎么解决？什么原因造成的

**Comment by xijaja** [comment]
看起来是 "vue-tsc" 版本的问题，我将它改为 "vue-tsc": "^2.0.29" 然后就可以了。
感谢你的反馈 @AduraK2 ，稍后我也升级一下模板中的依赖版本。

**Comment by xijaja** [comment]
以上问题已经解决，我将关闭这个 issues。
