### ISSUE TITLE
后续还会更多基础模板吗？

### ISSUE THREAD

**Issue by HHC26** [xijaja/wails-template-vue3#3]
例如使用Naive UI、Element UI、Ant Design等

**Comment by xijaja** [comment]
我理解 Naive UI、Element UI、Ant Design……都只是 UI 库，现在大火的恐怕是 Shadcn 首当其冲了。想要集成这些 UI 库非常简单，只需要将前端部分的依赖更换即可。

**Comment by xijaja** [comment]
哈哈，要说出模版的话，我倒是想出一个 svelte/kit + shadcnUI 的模版。

**Comment by xijaja** [comment]
太好了，就在刚刚我补充了一个新的模板：https://github.com/xijaja/wails-template-shadcn-svelte 
你可以玩玩看 @HHC26

**Comment by HHC26** [comment]
> 太好了，就在刚刚我补充了一个新的模板：https://github.com/xijaja/wails-template-shadcn-svelte 你可以玩玩看 @HHC26

好的，我试试，谢谢！
