### ISSUE TITLE
wails build 失败

### ISSUE THREAD

**Issue by xcbeyond** [xijaja/wails-template-vue3#4]
• Generating bindings: Done.
  • Installing frontend dependencies: Done.
Compiling frontend:     
    > demo@0.0.0 build /Users/xcbeyond/Downloads/demo/frontend
    > vue-tsc && vite build
    
    src/main.ts(3,17): error TS2306: File '/Users/xcbeyond/Downloads/demo/frontend/src/App.vue' is not a module.
    src/router.ts(4,19): error TS2306: File '/Users/xcbeyond/Downloads/demo/frontend/src/views/Login.vue' is not a module.
    src/router.ts(13,47): error TS2306: File '/Users/xcbeyond/Downloads/demo/frontend/src/views/Setup.vue' is not a module.
    src/views/Home.vue(2,24): error TS2306: File '/Users/xcbeyond/Downloads/demo/frontend/src/components/HelloWorld.vue' is not a module.
    
    TypeError: ctxVars.at is not a function
        at forEachInterpolationSegment (/Users/xcbeyond/Downloads/demo/frontend/node_modules/@vue/language-core/lib/codegen/template/interpolation.js:99:33)
        at forEachInterpolationSegment.next (<anonymous>)

**Comment by xijaja** [comment]
TypeError: ctxVars.at is not a function 错误，可能是 Node.js 版本过低。

如果未能解决，请提供更多有用信息，我将尝试重现并解决这个问题。
